name: whatimupto
author: Samuel JOSET
url: https://saxjst.com/
logo: /static/img/me.jpeg
favicon: /static/img/fav.png
description: Minimalist Open Source Developer
complement: For more information, checkout the links below
