name: Samuel JOSET
pageTitle: whatimupto
url: https://saxjst.com/
logo: /static/img/me.jpeg
favicon: /static/img/fav.png
description: Minimalist Open Source Developer
complement: For more information, checkout the links below
bio: Minimalist Open Source Developer
